# Generated by Django 5.0.1 on 2024-03-17 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('user_budget', models.IntegerField(verbose_name='Бюджет')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=20, verbose_name='Название расходов')),
                ('cost', models.FloatField(verbose_name='Расходы')),
                ('date_added', models.DateField(verbose_name='Дата произведения расходов')),
                ('user_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Расходы пользователя')),
            ],
        ),
    ]
