# Generated by Django 5.0.1 on 2024-03-16 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_name', models.CharField(max_length=30)),
                ('trans_type', models.CharField(max_length=3)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('journal_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAccounting.portfolio')),
            ],
        ),
    ]
